export const getBlogPosts = (t) => [
  {
    id: 1,
    slug: "leetcode",
    title: t("blog.blogs.leetcode.title"),
    excerpt: t("blog.blogs.leetcode.preview"),
    author: "Demid Krom",
    date: "24 Mai 2025",
    readTime: "10 min read",
    image: "/leet.png",
    tags: ["learning", "interview", "opinion"],
    component: "BlogPost2",
  },
  {
    id: 2,
    slug: "barcode-barcodes-barcode-barcodes-barcode-barcodes",
    title: t("blog.blogs.barcodes.title"),
    excerpt: t("blog.blogs.barcodes.preview"),
    author: "Demid Krom",
    date: "15 Februar 2025",
    readTime: "12 min read",
    image: "/regal.jpg",
    tags: ["bug", "barcodes", "learning", "diary"],
    component: "BlogPost3",
  },
  {
    id: 3,
    slug: "BlogPost1",
    title: t("blog.blogs.debt.title"),
    excerpt: t("blog.blogs.debt.preview"),
    author: "Demid Krom",
    date: "29 September 2024",
    readTime: "12 min read",
    image: "/schuld.png",
    tags: ["info", "planing"],
    component: "BlogPost1",
  },
]