export const getBlogPosts = (t) => [
  {
    id: 1,
    slug: "leetcode",
    title: t("blog.blogs.leetcode.title"),
    excerpt: t("blog.blogs.leetcode.preview"),
    author: t("common.fullName"),
    date: t("blog.blogs.leetcode.date"),
    readTime: t("blog.blogs.leetcode.readTime"),
    image: "/leet.png",
    component: "BlogPost2",
    isNew: true, // newest post gets the corner ribbon
  },
  {
    id: 2,
    slug: "barcodes",
    title: t("blog.blogs.barcodes.title"),
    excerpt: t("blog.blogs.barcodes.preview"),
    author: t("common.fullName"),
    date: t("blog.blogs.barcodes.date"),
    readTime: t("blog.blogs.barcodes.readTime"),
    image: "/regal.jpg",
    component: "BlogPost3",
  },
  {
    id: 3,
    slug: "technical_debt",
    title: t("blog.blogs.debt.title"),
    excerpt: t("blog.blogs.debt.preview"),
    author: t("common.fullName"),
    date: t("blog.blogs.debt.date"),
    readTime: t("blog.blogs.debt.readTime"),
    image: "/schuld.png",
    component: "BlogPost1",
  },
];
